export const enum SocketMessageTypes {
    JOIN_NOTIFICATION = "JOIN_NOTIFICATION",
    JOINED = "JOINED",
    MATCH = "MATCH",
    MATCHED = "MATCHED",
    MATCH_DONE = "MATCH_DONE",
    TIMER_START = "TIMER_START",
    TICK = "TICK",
    TIMER_DONE = "TIMER_DONE",
    TIMER_EXTEND = "TIMER_EXTEND",
    EXTENDED = "EXTENDED",
    HOST = "HOST",
    MATCHING_OVER = "MATCHING_OVER",
}
