export enum MessageTypes {
    JOIN_NOTIFICATION = "JOIN_NOTIFICATION",
    JOINED = "JOINED",
    MATCH = "MATCH",
    MATCHED = "MATCHED",
    TIMER_START = "TIMER_START",
    TICK = "TICK",
    TIMER_DONE = "TIMER_DONE",
    HOST = "HOST",
}
